package com.win.radio.manila.utilities;

public interface AccountCommands {
	
	/* JSP SCRIPTS */
	public String GET_ALL_USERS = "SELECT FORMAT(A.CREATE_DATE, 'MMM/dd/yyyy') AS CREATE_DATE, A.LAST_NAME, STAT.NAME AS 'ACCOUNT_STATUS', " + 
			"A.FIRST_NAME, T.NAME AS 'ACCOUNT_TYPE', A.USERNAME, A.EMAIL, FORMAT(A.UPDATE_DATE, 'MMM/dd/yyyy') AS UPDATE_DATE " + 
			"FROM ACCOUNT A " + 
			"LEFT JOIN ACCOUNT_TYPE T ON A.COD_TYPE = T.COD_TYPE " + 
			"LEFT JOIN ACCOUNT_STATUS STAT ON A.COD_STATUS = STAT.COD_STATUS " + 
			"WHERE A.COD_REGION = '" + CodeUtil.COD_REGION_MNL + "' " +
			"ORDER BY A.ID_ACCOUNT ASC";
	
	public String GET_ACCOUNT_TYPES = "SELECT COD_TYPE, NAME FROM ACCOUNT_TYPE";
	
	public String GET_ACCOUNT_DETAILS = "SELECT A.ID_ACCOUNT, A.LAST_NAME, A.FIRST_NAME, A.GENDER, ISNULL(D.DJ_NAME,'NONE') AS DJ_NAME " + 
			"A.COD_TYPE, T.NAME AS 'ACCOUNT_TYPE', A.USERNAME, A.EMAIL, A.MOBILE_NO " + 
			"FROM ACCOUNT A " + 
			"LEFT JOIN ACCOUNT_TYPE T ON A.COD_TYPE = T.COD_TYPE " + 
			"LEFT JOIN DJLIST D ON A.ID_ACCOUNT = D.ID_ACCOUNT " + 
			"WHERE A.ID_ACCOUNT = ?";
	
	/* CONTROLLER SCRIPTS */
	public String GET_CREDENTIALS = "SELECT ACCOUNT.ID_ACCOUNT, ACCOUNT.USERNAME, ACCOUNT.PASSWORD, ACCOUNT.COD_TYPE, ACCOUNT.IND_CHANGE_PWD, " +
			"ACCOUNT_TYPE.NAME FROM ACCOUNT INNER JOIN ACCOUNT_TYPE ON ACCOUNT.COD_TYPE = ACCOUNT_TYPE.COD_TYPE WHERE USERNAME = ? " +
			"AND COD_REGION = '" + CodeUtil.COD_REGION_MNL + "'";
	
	public String GET_USERNAME = "SELECT USERNAME FROM ACCOUNT WHERE USERNAME = ? " +
			"AND COD_REGION = '" + CodeUtil.COD_REGION_MNL + "'";
	
	public String GET_EMAIL = "SELECT EMAIL FROM ACCOUNT WHERE EMAIL = ? " +
			"AND COD_REGION = '" + CodeUtil.COD_REGION_MNL + "'";
	
	public String GET_CONTACT_DETAILS = "SELECT USERNAME, EMAIL FROM ACCOUNT WHERE ID_ACCOUNT = ?";
	
	public String ADD_ACCOUNT = "INSERT INTO ACCOUNT (CREATE_DATE, UPDATE_DATE, UPDATE_USER, COD_TYPE, " + 
			"	USERNAME, PASSWORD, LAST_NAME, FIRST_NAME, GENDER, " + 
			"	MOBILE_NO, EMAIL, COD_STATUS, COD_REGION, IND_CHANGE_PWD) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1)";
	
	public String UPDATE_ACCOUNT = "UPDATE ACCOUNT "
			+ "SET UPDATE_DATE = ?, UPDATE_USER = ?, COD_TYPE = ?, USERNAME = ?, "
			+ "EMAIL = ?, LAST_NAME = ?, FIRST_NAME = ?, GENDER = ?,"
			+ "MOBILE_NO = ? WHERE ID_ACCOUNT = ?";
	
	public String CHANGE_PASSWORD = "UPDATE ACCOUNT " + 
			"SET UPDATE_DATE = ?, UPDATE_USER = ?, PASSWORD = ?, IND_CHANGE_PWD = ? " + 
			"WHERE ID_ACCOUNT = ?";
}
