package com.win.radio.manila.utilities;

public interface AccountCommands {
	
	/* JSP SCRIPTS */
	public String GET_ALL_USERS = "SELECT FORMAT(A.CREATE_DATE, 'MMM/dd/yyyy') AS CREATE_DATE, A.LAST_NAME, STAT.NAME AS 'ACCOUNT_STATUS', " + 
			"A.FIRST_NAME, T.NAME AS 'ACCOUNT_TYPE', A.USERNAME, A.EMAIL, FORMAT(A.UPDATE_DATE, 'MMM/dd/yyyy') AS UPDATE_DATE " + 
			"FROM ACCOUNT A " + 
			"LEFT JOIN ACCOUNT_TYPE T ON A.COD_TYPE = T.COD_TYPE " + 
			"LEFT JOIN ACCOUNT_STATUS STAT ON A.COD_STATUS = STAT.COD_STATUS " + 
			"WHERE A.COD_REGION = '" + CodeUtil.COD_REGION_MNL + "' " +
			"ORDER BY A.ID_ACCOUNT ASC";
	
	public String GET_ACCOUNT_TYPES = "SELECT COD_TYPE, NAME FROM ACCOUNT_TYPE";
	
	public String GET_IND_CHANGE_PWD = "SELECT IND_CHANGE_PWD FROM ACCOUNT WHERE ID_ACCOUNT = ? AND " +
			"COD_REGION = '" + CodeUtil.COD_REGION_MNL + "'";
	
	/* CONTROLLER SCRIPTS */
	public String GET_CREDENTIALS = "SELECT ID_ACCOUNT, USERNAME, PASSWORD, COD_TYPE, IND_CHANGE_PWD FROM ACCOUNT " +
			"WHERE USERNAME = ? AND COD_REGION = '" + CodeUtil.COD_REGION_MNL + "'";
	
	public String GET_USERNAME = "SELECT USERNAME FROM ACCOUNT WHERE USERNAME = ? " +
			"AND COD_REGION = '" + CodeUtil.COD_REGION_MNL + "'";
	
	public String GET_EMAIL = "SELECT EMAIL FROM ACCOUNT WHERE EMAIL = ? " +
			"AND COD_REGION = '" + CodeUtil.COD_REGION_MNL + "'";
	
	public String ADD_ACCOUNT = "INSERT INTO ACCOUNT (CREATE_DATE, UPDATE_DATE, UPDATE_USER, COD_TYPE, " + 
			"	USERNAME, PASSWORD, LAST_NAME, FIRST_NAME, GENDER, " + 
			"	MOBILE_NO, EMAIL, COD_STATUS, COD_REGION, IND_CHANGE_PWD) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1)";
	
}
