package com.win.radio.manila.utilities;

public interface BannerCommands {

	/* JSP SCRIPTS */

	public String GET_BANNER_ADS = "SELECT DATE_FORMAT(B.UPDATE_DATE, '%b %d, %Y %h:%i') AS UPDATE_DATE, "
			+ "B.ID_AD, A.USERNAME, B.BRAND, B.STATUS FROM BANNER B "
			+ "LEFT JOIN ACCOUNT A ON B.UPDATE_USER = A.ID_ACCOUNT WHERE B.COD_REGION = '"
			+ CodeUtil.COD_REGION_MNL + "' ORDER BY B.ID_AD DESC";

	/* CONTROLLER SCRIPTS */

	public String ADD_SPONSOR = "INSERT INTO BANNER (CREATE_DATE, UPDATE_DATE, UPDATE_USER, BRAND, IMAGE, "
			+ "STATUS, COD_REGION) VALUES (?, ?, ?, ?, ?, ?, ?)";
	
	public String GET_SPONSOR_DETAILS = "SELECT ID_AD, BRAND, IMAGE, STATUS, UPDATE_DATE, UPDATE_USER FROM BANNER WHERE ID_AD = ?";
	
	public String UPDATE_SPONSOR = "UPDATE BANNER SET UPDATE_DATE = ?, UPDATE_USER = ?, BRAND = ?, IMAGE = ? "
			+ "WHERE ID_AD = ?";
	
	public String UPDATE_SPONSOR_STATUS = "UPDATE BANNER SET UPDATE_DATE = ?, UPDATE_USER = ?, STATUS = ? WHERE ID_AD = ?";

}
