package com.win.radio.manila.utilities;

public interface DramaCommands {

	/* JSP SCRIPTS */

	public String GET_ALL_DRAMA = "SELECT DATE_FORMAT(E.CREATE_DATE, '%b %d, %Y %h:%i') as DATE_POSTED, "
			+ "DATE_FORMAT(E.UPDATE_DATE, '%b %d, %Y %h:%i') as UPDATE_DATE, "
			+ "E.ID_EPISODE, E.TITLE, E.DESCRIPTION, E.STATUS, A.USERNAME "
			+ "FROM EPISODE E LEFT JOIN ACCOUNT A ON E.UPDATE_USER = A.ID_ACCOUNT "
			+ "WHERE E.COD_REGION LIKE ? ORDER BY E.ID_EPISODE ASC";
		
	public String GET_ALL_EPISODES = "SELECT FORMAT(CREATE_DATE, 'MMM dd, yyyy') AS DATE_POSTED, ID_EPISODE, " + 
			"TITLE, DESCRIPTION, FILENAME, IMAGE, STATUS " + 
			"FROM EPISODE " + 
			"WHERE COD_REGION = ? AND STATUS LIKE ? " + 
			"ORDER BY ID_EPISODE DESC";

	public String GET_DRAMA_DETAILS = "SELECT ID_EPISODE, TITLE, DESCRIPTION, FILENAME, IMAGE, STATUS FROM EPISODE WHERE ID_EPISODE = ?";

	/* CONTROLLER SCRIPTS */

	public String ADD_DRAMA = "INSERT INTO EPISODE (CREATE_DATE, UPDATE_DATE, UPDATE_USER, TITLE, DESCRIPTION, "
			+ "FILENAME, IMAGE, STATUS, COD_REGION) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";

	public String UPDATE_DRAMA = "UPDATE EPISODE SET UPDATE_DATE = ?, UPDATE_USER = ?, TITLE = ?, DESCRIPTION = ?, FILENAME = ?, IMAGE = ? "
			+ "WHERE ID_EPISODE = ?";

	public String UPDATE_EPISODE_STATUS = "UPDATE EPISODE SET UPDATE_DATE = ?, "
			+ "UPDATE_USER = ?, STATUS = ? WHERE ID_EPISODE = ?";


}
