package com.win.radio.manila.utilities;

public interface DramaCommands {

	/* JSP SCRIPTS */

	/* Marvin - Codes Start */

	public String GET_ALL_DRAMA = "SELECT FORMAT(E.CREATE_DATE, 'MMM/dd/yyyy') AS CREATE_DATE, FORMAT(E.UPDATE_DATE, "
			+ "'MMM/dd/yyyy') AS UPDATE_DATE, E.ID_EPISODE, E.TITLE, E.DESCRIPTION, E.STATUS, A.USERNAME "
			+ "FROM EPISODE E LEFT JOIN ACCOUNT A ON E.UPDATE_USER = A.ID_ACCOUNT " + "WHERE E.COD_REGION = '"
			+ CodeUtil.COD_REGION_MNL + "' ORDER BY E.ID_EPISODE ASC";

	public String GET_DRAMA_DETAILS = "SELECT ID_EPISODE, TITLE, DESCRIPTION, FILENAME, IMAGE, STATUS FROM EPISODE WHERE ID_EPISODE = ?";

	/* CONTROLLER SCRIPTS */

	public String ADD_DRAMA = "INSERT INTO EPISODE (CREATE_DATE, UPDATE_DATE, UPDATE_USER, TITLE, DESCRIPTION, "
			+ "FILENAME, IMAGE, STATUS, COD_REGION) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";

	public String UPDATE_DRAMA = "UPDATE EPISODE SET UPDATE_DATE = ?, UPDATE_USER = ?, TITLE = ?, DESCRIPTION = ?, FILENAME = ?, IMAGE = ? "
			+ "WHERE ID_EPISODE = ?";

	public String UPDATE_EPISODE_STATUS = "UPDATE EPISODE SET UPDATE_DATE = ?, "
			+ "UPDATE_USER = ?, STATUS = ? WHERE ID_EPISODE = ?";

	/* Marvin - Codes End */

}
