package com.win.radio.manila.utilities;

public interface PSCommands {

	//adminNewProgramSchedule
	
	public String GET_DJ_NAME = "SELECT D.DJ_NAME, D.ID_ACCOUNT FROM DJLIST D " + 
			"LEFT JOIN ACCOUNT A ON D.ID_ACCOUNT = A.ID_ACCOUNT " + 
			"WHERE A.COD_STATUS = '" + CodeUtil.COD_STATUS_ACTIVE + "' ";

	public String GET_ALL_PS_NAME = "SELECT PROG_NAME FROM PROGRAM WHERE PROG_NAME = ?";

	public String ADD_PROGRAM = "INSERT INTO PROGRAM (CREATE_DATE, UPDATE_DATE, " +
			"UPDATE_USER, PROG_NAME, DESCRIPTION, SCHEDULE, PROG_DJ, COD_REGION, STATUS) " +
			"VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)"; 
	
	//adminProgramSchedule
	
	public String GET_ALL_PROGRAM = "SELECT ID_PROGRAM, FORMAT(CREATE_DATE, 'MMM/dd/yyyy') AS CREATE_DATE, "+
			"PROG_DJ, PROG_NAME, DESCRIPTION, SCHEDULE, STATUS FROM PROGRAM ORDER BY STATUS ASC";
	
	public String GET_PROGRAM_DJ_NAME = "SELECT D.DJ_NAME FROM DJLIST D " + 
	"LEFT JOIN ACCOUNT A ON D.ID_ACCOUNT = A.ID_ACCOUNT " + 
	"WHERE A.COD_STATUS = '" + CodeUtil.COD_STATUS_ACTIVE + "' AND D.ID_ACCOUNT = ? ";
	
	//adminUpdateProgram
	
	public String GET_PROGRAM_DETAILS = "SELECT PROG_NAME, DESCRIPTION, SCHEDULE, PROG_DJ, STATUS FROM PROGRAM WHERE ID_PROGRAM = ?";

	public String UPDATE_PROGRAM = "UPDATE PROGRAM SET UPDATE_DATE = ?, UPDATE_USER = ?, PROG_NAME = ?, " +
			"DESCRIPTION = ?, SCHEDULE = ?, PROG_DJ = ?, STATUS = ? WHERE ID_PROGRAM = ?";
	
}

