package com.win.radio.manila.utilities;

public interface SocialMediaCommands {

	/*JSP SCRIPTS*/
	public String UPDATE_SOCIAL_LINK = "UPDATE SOCIAL_MEDIA " +
			"SET UPDATE_DATE = ?, UPDATE_USER = ?, URL = ? WHERE ID_MEDIA = ?";
		
	
	/* CONTROLLER SCRIPTS */
	public String ADD_NEW_SOCIAL_MEDIA = "INSERT INTO SOCIAL_MEDIA (CREATE_DATE, UPDATE_DATE, "+
			"UPDATE_USER, NAME, URL, REGION) VALUES (?, ?, ?, ?, ?, ?)"; 

	public String GET_SOCIAL_MEDIA_ACCTS = "SELECT FACEBOOK.ID_MEDIA AS 'FACEBOOK_ID', FACEBOOK.URL AS 'FACEBOOK_URL', " + 
			"AUDIO_STREAM.ID_MEDIA AS 'AUDIO_STREAM_ID', AUDIO_STREAM.URL AS 'AUDIO_STREAM_URL', " + 
			"VIDEO_STREAM.ID_MEDIA AS 'VIDEO_STREAM_ID', VIDEO_STREAM.URL AS 'VIDEO_STREAM_URL' FROM " + 
			"(SELECT ID_MEDIA, URL FROM SOCIAL_MEDIA WHERE NAME ='Facebook' AND COD_REGION = ?) FACEBOOK, " + 
			"(SELECT ID_MEDIA, URL FROM SOCIAL_MEDIA WHERE NAME ='Audio Stream' AND COD_REGION = ?) AUDIO_STREAM, " + 
			"(SELECT ID_MEDIA, URL FROM SOCIAL_MEDIA WHERE NAME ='Video Stream' AND COD_REGION = ?) VIDEO_STREAM";
	
}
