package com.win.radio.manila.utilities;

public interface SQLCommands {

	String DS_SOURCE="java:comp/env/jdbc/WinRadioDB";
	String CONNECTION_NOT_FOUND="Invalid connection. Unable to process request.";
	
	public String GET_ALL_ACCOUNTS = "SELECT * FROM ACCOUNT";
	
	/* JSP SCRIPTS */
	public String GET_EVENT_LOGS = "SELECT TOP (10) FORMAT(E.CREATE_DATE, 'MMM dd hh:ss') as 'CREATE_DATE', A.FIRST_NAME + ' ' + A.LAST_NAME + ' ' + E.DESCRIPTION AS 'EVENT' " + 
			"FROM EVENT_LOG E " + 
			"LEFT JOIN ACCOUNT A ON E.UPDATE_USER = A.ID_ACCOUNT " + 
			"ORDER BY ID_LOG DESC";
	public String GET_ALL_USERS = "SELECT FORMAT(A.CREATE_DATE, 'MMM/dd/yyyy') AS CREATE_DATE, A.LAST_NAME, STAT.NAME_TYPE AS 'ACCOUNT_STATUS', " + 
			"A.FIRST_NAME, P.NAME_TYPE AS 'ACCOUNT_TYPE', A.USERNAME, A.EMAIL, FORMAT(A.UPDATE_DATE, 'MMM/dd/yyyy') AS UPDATE_DATE " + 
			"FROM ACCOUNT A " + 
			"LEFT JOIN USER_PROFILE P ON A.COD_PROFILE = P.COD_PROFILE " + 
			"LEFT JOIN ACCOUNT_STATUS STAT ON A.COD_STATUS = STAT.COD_STATUS " + 
			"ORDER BY A.ID_ACCOUNT ASC";
	public String GET_USER_PROFILES = "SELECT COD_PROFILE, NAME_TYPE FROM USER_PROFILE";
	
	
	/* CONTROLLER SCRIPTS */
	public String ADD_ACCOUNT = "INSERT INTO ACCOUNT (CREATE_DATE, UPDATE_DATE, UPDATE_USER, COD_PROFILE, " + 
			"	USERNAME, PASSWORD, SCREEN_NAME, LAST_NAME, FIRST_NAME, GENDER, " + 
			"	MOBILE_NO, EMAIL, COD_STATUS) VALUES (?, ?, 0, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
	
}
